[package]
name = "lokey"
version = "0.0.0"
edition = "2024"
authors = ["Niklas Sauter <niklas@n1ks.net>"]
repository = "https://github.com/nn1ks/lokey"
license = "Apache-2.0 OR MIT"

[features]
default = ["usb"]

defmt = [
  "dep:defmt",
  "embassy-executor/defmt",
  "embassy-futures/defmt",
  "embassy-rp?/defmt",
  "embassy-sync/defmt",
  "embassy-time/defmt",
  "embassy-usb/defmt",
  "embedded-hal/defmt-03",
  "embedded-hal-async/defmt-03",
  "sequential-storage/defmt-03",
  "usbd-hid?/defmt",
]

usb = [
  "dep:embassy-usb",
  "dep:usbd-hid",
]
ble = [
  "dep:usbd-hid",
  "dep:ssmarshal",
]

rp2040 = [
  "embassy-executor/arch-cortex-m",
  "dep:embassy-rp",
  "embassy-rp/rp2040"
]

[dependencies]
defmt = { version = "0.3.5", features = ["alloc"], optional = true }
embassy-executor = { version = "0.7.0", features = ["executor-thread", "executor-interrupt", "nightly"] }
embassy-futures = "0.1.1"
embassy-rp = { version = "0.3.1", features = ["critical-section-impl", "time-driver"], optional = true }
embassy-sync = "0.6.2"
embassy-time = "0.4.0"
embassy-usb = { version = "0.4.0", features = ["usbd-hid"], optional = true }
embedded-alloc = "0.6.0"
embedded-hal = "1.0.0"
embedded-hal-async = "1.0.0"
embedded-storage-async = "0.4.1"
futures-util = { version = "0.3.30", default-features = false, features = ["alloc"] }
generic-array = "1.0.0"
lokey_macros = { path = "../lokey_macros" }
once_cell = { version = "1.19.0", default-features = false, features = ["critical-section"] }
portable-atomic = { version = "1.6.0", default-features = false, features = ["critical-section", "require-cas"] }
portable-atomic-util = { version = "0.2.0", features = ["alloc"] }
sequential-storage = "4.0.1"
ssmarshal = { version = "1.0.0", default-features = false, optional = true }
typenum = "1.17.0"
usbd-hid = { version = "0.8.2", optional = true }

[dev-dependencies]
cortex-m-rt = "0.7.0"

[package.metadata.docs.rs]
features = ["defmt", "usb", "ble"]
