[package]
name = "lokey"
version = "0.0.1"
edition = "2024"
authors = ["Niklas Sauter <niklas@n1ks.net>"]
repository = "https://github.com/nn1ks/lokey"
license = "Apache-2.0 OR MIT"
description = "A firmware framework for input devices"
readme = "../README.md"
categories = ["embedded", "no-std"]
keywords = ["keyboard", "firmware"]

[features]
default = ["macros"]

## Enables macros.
macros = [
  "dep:lokey_macros",
]

## Enables logging via [defmt](https://docs.rs/defmt/latest/defmt).
defmt = [
  "dep:defmt",
  "embassy-futures/defmt",
  "embassy-nrf?/defmt",
  "embassy-rp?/defmt",
  "embassy-sync/defmt",
  "embassy-time/defmt",
  "embassy-usb/defmt",
  "embedded-hal/defmt-03",
  "embedded-hal-async/defmt-03",
  "trouble-host?/defmt",
  "nrf-sdc?/defmt",
  "nrf-mpsl?/defmt",
  "sequential-storage/defmt-03",
  "usbd-hid?/defmt",
]

#! #### Transports

## Enables the external USB transport.
external-usb = [
  "dep:embassy-usb",
]

## Enables a generic USB transport for human interface devices.
external-usb-hid = [
  "dep:usbd-hid",
]

## Enables the external Bluetooth Low Energy (BLE) transport.
external-ble = [
  "dep:trouble-host",
  "dep:rand_chacha",
]

## Enables the internal Bluetooth Low Energy (BLE) transport.
internal-ble = [
  "dep:trouble-host",
  "dep:rand_chacha",
]

#! #### Microcontrollers

## Enables support for the nRF52840 microcontroller.
nrf52840 = [
  "dep:embassy-nrf",
  "embassy-nrf/nrf52840",
  "dep:nrf-mpsl",
  "dep:nrf-sdc",
  "nrf-mpsl?/nrf52840",
  "nrf-sdc?/nrf52840",
]

## Enables support for the RP2040 microcontroller.
rp2040 = [
  "dep:embassy-rp",
  "embassy-rp/rp2040",
]

[dependencies]
bitcode = { git = "https://github.com/nn1ks/bitcode", branch = "fix-arc-impl", default-features = false, features = ["derive"] }
defmt = { version = "0.3.5", features = ["alloc"], optional = true }
document-features = "0.2.11"
dyn-clone = { git = "https://github.com/nn1ks/dyn-clone", branch = "fix-arc-usage" }
embassy-futures = "0.1.1"
embassy-nrf = { version = "0.3.1", features = ["gpiote", "time-driver-rtc1", "nfc-pins-as-gpio"], optional = true }
embassy-rp = { version = "0.4.0", features = ["critical-section-impl", "time-driver"], optional = true }
embassy-sync = "0.6.2"
# TODO: Remove once a new version of embassy-sync is released (with RwLock)
embassy-sync-new = { git = "https://github.com/embassy-rs/embassy", package = "embassy-sync" }
embassy-time = "0.4.0"
embassy-usb = { version = "0.4.0", features = ["usbd-hid"], optional = true }
embedded-alloc = "0.6.0"
embedded-hal = "1.0.0"
embedded-hal-async = "1.0.0"
embedded-storage-async = "0.4.1"
futures-util = { version = "0.3.30", default-features = false, features = ["alloc"] }
generic-array = "1.0.0"
lokey_macros = { path = "../lokey_macros", version = "0.0.1", optional = true }
nrf-mpsl = { git = "https://github.com/nn1ks/nrf-sdc", features = ["critical-section-impl"], optional = true }
nrf-sdc = { git = "https://github.com/nn1ks/nrf-sdc", features = ["central", "peripheral"], optional = true }
portable-atomic = { version = "1.6.0", default-features = false, features = ["critical-section", "require-cas"] }
portable-atomic-util = { version = "0.2.0", features = ["alloc"] }
rand_chacha = { version = "0.3.1", default-features = false, optional = true }
seq-macro = "0.3.6"
sequential-storage = "4.0.1"
static_cell = "2.1.0"
trouble-host = { git = "https://github.com/embassy-rs/trouble", rev = "3d77c0b", features = ["security"], optional = true }
typenum = "1.17.0"
usbd-hid = { version = "0.8.2", optional = true }

[dev-dependencies]
cortex-m-rt = "0.7.0"
embassy-executor = { version = "0.7.0", features = ["arch-cortex-m", "executor-thread"] }

[package.metadata.docs.rs]
features = ["defmt", "external-usb", "external-usb-hid", "external-ble", "internal-ble"]
