[package]
name = "lokey"
version = "0.0.0"
edition = "2024"
authors = ["Niklas Sauter <niklas@n1ks.net>"]
repository = "https://github.com/nn1ks/lokey"
license = "Apache-2.0 OR MIT"

[features]
default = ["usb"]

usb = [
  "dep:embassy-usb",
  "dep:usbd-hid",
]
ble = [
  "dep:usbd-hid",
  "dep:ssmarshal",
  "nrf-softdevice?/ble-sec",
  "nrf-softdevice?/ble-central",
  "nrf-softdevice?/ble-peripheral",
  "nrf-softdevice?/ble-gatt-server",
  "nrf-softdevice?/ble-gatt-client"
]

nrf52840 = [
  "embassy-executor/arch-cortex-m",
  "dep:embassy-nrf",
  "embassy-nrf/nrf52840",
  "dep:nrf-softdevice",
  "nrf-softdevice?/nrf52840",
  "nrf-softdevice?/s140"
]
rp2040 = [
  "embassy-executor/arch-cortex-m",
  "dep:embassy-rp",
  "embassy-rp/rp2040"
]

[dependencies]
defmt = { version = "0.3.5", features = ["alloc"] }
embassy-executor = { version = "0.7.0", features = ["executor-thread", "executor-interrupt", "nightly", "defmt"] }
embassy-futures = { version = "0.1.1", features = ["defmt"] }
embassy-nrf = { version = "0.3.1", features = ["gpiote", "time-driver-rtc1", "nfc-pins-as-gpio", "defmt"], optional = true }
embassy-rp = { version = "0.3.1", features = ["critical-section-impl", "time-driver", "defmt"], optional = true }
embassy-sync = { version = "0.6.2", features = ["defmt"] }
embassy-time = { version = "0.4.0", features = ["defmt"] }
embassy-usb = { version = "0.4.0", features = ["usbd-hid", "defmt"], optional = true }
embedded-alloc = "0.6.0"
embedded-hal = { version = "1.0.0", features = ["defmt-03"] }
embedded-hal-async = { version = "1.0.0", features = ["defmt-03"] }
embedded-storage-async = "0.4.1"
futures-util = { version = "0.3.30", default-features = false, features = ["alloc"] }
generic-array = "1.0.0"
lokey_macros = { path = "../lokey_macros" }
nrf-softdevice = { git = "https://github.com/embassy-rs/nrf-softdevice", rev = "bb1600b728c8acbaecf974741ee5867b472289f3", features = ["critical-section-impl", "usable-from-interrupts", "defmt"], optional = true }
once_cell = { version = "1.19.0", default-features = false, features = ["critical-section"] }
portable-atomic = { version = "1.6.0", default-features = false, features = ["critical-section", "require-cas"] }
portable-atomic-util = { version = "0.2.0", features = ["alloc"] }
sequential-storage = { version = "4.0.1", features = ["defmt-03"] }
ssmarshal = { version = "1.0.0", default-features = false, optional = true }
switch-hal = { git = "https://github.com/daniel-dbg-ginsburg/switch-hal", branch = "hal-update", features = ["async"] }
typenum = "1.17.0"
usbd-hid = { version = "0.8.2", features = ["defmt"], optional = true }

[dev-dependencies]
cortex-m-rt = "0.7.0"
