[package]
name = "lokey"
version = "0.0.0"
edition = "2021"
authors = ["Niklas Sauter <niklas@n1ks.net>"]
repository = "https://github.com/nn1ks/lokey"
license = "Apache-2.0 OR MIT"

[features]
default = ["usb"]

usb = [
  "dep:embassy-usb",
  "dep:usbd-hid",
]
ble = [
  "dep:usbd-hid",
  "dep:ssmarshal",
  "nrf-softdevice?/ble-sec",
  "nrf-softdevice?/ble-central",
  "nrf-softdevice?/ble-peripheral",
  "nrf-softdevice?/ble-gatt-server",
  "nrf-softdevice?/ble-gatt-client"
]

nrf52840 = [
  "embassy-executor/arch-cortex-m",
  "dep:embassy-nrf",
  "embassy-nrf/nrf52840",
  "dep:nrf-softdevice",
  "nrf-softdevice?/nrf52840",
  "nrf-softdevice?/s140"
]

[dependencies]
defmt = { version = "0.3.5", features = ["alloc"] }
embassy-executor = { version = "0.5.0", features = ["executor-thread", "executor-interrupt", "integrated-timers", "nightly", "defmt"] }
embassy-futures = { version = "0.1.1", features = ["defmt"] }
embassy-nrf = { version = "0.1.0", features = ["gpiote", "time-driver-rtc1", "nfc-pins-as-gpio", "defmt"], optional = true }
embassy-sync = { version = "0.5.0", features = ["defmt"] }
embassy-time = { version = "0.3.0", features = ["defmt"] }
embassy-usb = { version = "0.1.0", features = ["usbd-hid", "defmt"], optional = true }
embedded-alloc = "0.5.0"
embedded-hal = { version = "1.0.0", features = ["defmt-03"] }
embedded-hal-async = { version = "1.0.0", features = ["defmt-03"] }
embedded-storage-async = "0.4.1"
futures-util = { version = "0.3.30", default-features = false, features = ["alloc"] }
lokey_macros = { path = "../lokey_macros" }
nrf-softdevice = { git = "https://github.com/embassy-rs/nrf-softdevice", rev = "3c53b8c454cc9331082053033485e713abcadbb5", features = ["critical-section-impl", "usable-from-interrupts", "defmt"], optional = true }
sequential-storage = { version = "2.0.2", features = ["defmt-03"] }
ssmarshal = { version = "1.0.0", default-features = false, optional = true }
static_cell = { version = "2.1.0", features = ["nightly"] }
switch-hal = { git = "https://github.com/daniel-dbg-ginsburg/switch-hal", branch = "hal-update", features = ["async"] }
usbd-hid = { version = "0.6.0", features = ["defmt"], optional = true }

[dev-dependencies]
cortex-m-rt = "0.7.0"
