[target.thumbv7em-none-eabihf]
runner = "probe-rs run --chip nRF52840_xxAA"

[build]
target = "thumbv7em-none-eabihf"

[profile.dev]
lto = true
opt-level = "s"
codegen-units = 1

[profile.release]
lto = true
opt-level = "s"
incremental = false
codegen-units = 1
debug = 2

[env]
DEFMT_LOG = "debug"
