[package]
name = "keyboard_rp2040"
version = "0.0.0"
edition = "2024"

[dependencies]
cortex-m-rt = "0.7.0"
defmt = "0.3.6"
defmt-rtt = "0.4.0"
embassy-executor = { version = "0.7.0", features = ["executor-thread"] }
embassy-rp = "0.3.1"
embassy-time = "0.4.0"
lokey = { path = "../../lokey", features = ["rp2040", "ble", "defmt"] }
panic-probe = { version = "0.3.1", features = ["print-defmt"] }
switch-hal = { git = "https://github.com/daniel-dbg-ginsburg/switch-hal", branch = "hal-update", features = ["async"] }
