[package]
name = "keyboard_rp2040"
version = "0.0.0"
edition = "2024"

[features]
defmt = [
    "dep:defmt",
    "dep:defmt-rtt",
    "lokey/defmt",
    "lokey_common/defmt",
    "lokey_keyboard/defmt",
    "panic-probe/print-defmt",
]

[dependencies]
cortex-m-rt = "0.7.0"
defmt = { version = "0.3.6", optional = true }
defmt-rtt = { version = "0.4.0", optional = true }
embassy-executor = { version = "0.7.0", features = ["arch-cortex-m", "executor-thread", "nightly"] }
embassy-rp = "0.4.0"
embassy-time = "0.4.0"
lokey = { path = "../../lokey", features = ["rp2040", "external-usb"] }
lokey_common = { path = "../../lokey_common", features = ["layer", "blink"] }
lokey_keyboard = { path = "../../lokey_keyboard", features = ["external-usb"] }
panic-probe = "0.3.1"
switch-hal = { git = "https://github.com/daniel-dbg-ginsburg/switch-hal", branch = "hal-update", features = ["async"] }
