name: Rust

on:
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "master" ]

env:
  CARGO_TERM_COLOR: always
  RUSTFLAGS: -D warnings

jobs:
  build:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        mcu: [no_mcu, nrf52840]
        features: ["", "usb", "ble", "usb ble"]
        include:
          - mcu: no_mcu
            target: thumbv7em-none-eabihf
            mcu_features: ""
          - mcu: nrf52840
            target: thumbv7em-none-eabihf
            mcu_features: "nrf52840"
        exclude:
          - mcu: nrf52840
            features: ""
          - mcu: nrf52840
            features: "usb"
    steps:
    - uses: actions/checkout@v4
    - name: Build
      run: cargo build --verbose --target ${{ matrix.target }} --no-default-features --features '${{ matrix.features }} ${{ matrix.mcu_features }}'
    - name: Run tests
      if: matrix.mcu != 'no_mcu'
      run: cargo test --verbose --doc -Zdoctest-xcompile --target ${{ matrix.target }} --no-default-features --features '${{ matrix.features }} ${{ matrix.mcu_features }}'
  format:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4
    - name: Check formatting
      run: cargo fmt --verbose --check
  clippy:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        mcu: [nrf52840]
        include:
          - mcu: nrf52840
            target: thumbv7em-none-eabihf
            mcu_features: "nrf52840"
    steps:
    - uses: actions/checkout@v4
    - name: Run clippy
      run: cargo clippy --verbose --target ${{ matrix.target }} --no-default-features --features "${{ matrix.mcu_features }} usb ble" -- -D warnings
