name: Rust

on:
  push:
    branches: [ "master" ]
    paths-ignore:
      - docs/**
  pull_request:
    branches: [ "master" ]
    paths-ignore:
      - docs/**

env:
  CARGO_TERM_COLOR: always
  RUSTFLAGS: -D warnings
  DEFMT_LOG: trace

jobs:
  format:
    runs-on: ubuntu-latest
    if: always()
    steps:
      - uses: actions/checkout@v4
      - name: Print rust version
        run: |
          rustc --version
          cargo --version
      - name: Check formatting
        run: cargo fmt --verbose --check
  lokey:
    runs-on: ubuntu-latest
    if: always()
    strategy:
      fail-fast: false
      matrix:
        target: ["x86_64-unknown-linux-gnu", "thumbv7em-none-eabihf", "thumbv6m-none-eabi"]
    env:
      FEATURE_COMBINATIONS: ";macros;defmt;macros defmt"
    steps:
      - uses: actions/checkout@v4
      - name: Print rust version
        run: |
          rustc --version
          cargo --version
      - name: Build
        run: |
          export IFS=";"
          for features in $FEATURE_COMBINATIONS; do
            echo "::group::Features: \"$features\""
            cargo build -p lokey --verbose --target ${{ matrix.target }} --no-default-features --features "$features"
            echo "::endgroup::"
          done
      - name: Run clippy
        run: |
          export IFS=";"
          for features in $FEATURE_COMBINATIONS; do
            echo "::group::Features: \"$features\""
            cargo clippy -p lokey --verbose --target ${{ matrix.target }} --no-default-features --features "$features"
            echo "::endgroup::"
          done
      - name: Run tests
        if: matrix.target == 'x86_64-unknown-linux-gnu'
        run: |
          cargo test -p lokey --verbose --target ${{ matrix.target }}
  lokey-usb:
    runs-on: ubuntu-latest
    if: always()
    strategy:
      fail-fast: false
      matrix:
        target: ["x86_64-unknown-linux-gnu", "thumbv7em-none-eabihf", "thumbv6m-none-eabi"]
    env:
      FEATURE_COMBINATIONS: ";defmt;macros defmt"
    steps:
      - uses: actions/checkout@v4
      - name: Print rust version
        run: |
          rustc --version
          cargo --version
      - name: Build
        run: |
          export IFS=";"
          for features in $FEATURE_COMBINATIONS; do
            echo "::group::Features: \"$features\""
            cargo build -p lokey-usb --verbose --target ${{ matrix.target }} --no-default-features --features "$features"
            echo "::endgroup::"
          done
      - name: Run clippy
        run: |
          export IFS=";"
          for features in $FEATURE_COMBINATIONS; do
            echo "::group::Features: \"$features\""
            cargo clippy -p lokey-usb --verbose --target ${{ matrix.target }} --no-default-features --features "$features"
            echo "::endgroup::"
          done
      - name: Run tests
        if: matrix.target == 'x86_64-unknown-linux-gnu'
        run: |
          cargo test -p lokey-usb --verbose --target ${{ matrix.target }}
  lokey-ble:
    runs-on: ubuntu-latest
    if: always()
    strategy:
      fail-fast: false
      matrix:
        target: ["x86_64-unknown-linux-gnu", "thumbv7em-none-eabihf", "thumbv6m-none-eabi"]
    env:
      FEATURE_COMBINATIONS: ";defmt;macros defmt"
    steps:
      - uses: actions/checkout@v4
      - name: Print rust version
        run: |
          rustc --version
          cargo --version
      - name: Build
        run: |
          export IFS=";"
          for features in $FEATURE_COMBINATIONS; do
            echo "::group::Features: \"$features\""
            cargo build -p lokey-ble --verbose --target ${{ matrix.target }} --no-default-features --features "$features"
            echo "::endgroup::"
          done
      - name: Run clippy
        run: |
          export IFS=";"
          for features in $FEATURE_COMBINATIONS; do
            echo "::group::Features: \"$features\""
            cargo clippy -p lokey-ble --verbose --target ${{ matrix.target }} --no-default-features --features "$features"
            echo "::endgroup::"
          done
      - name: Run tests
        if: matrix.target == 'x86_64-unknown-linux-gnu'
        run: |
          cargo test -p lokey-ble --verbose --target ${{ matrix.target }}
  lokey-usb-ble:
    runs-on: ubuntu-latest
    if: always()
    strategy:
      fail-fast: false
      matrix:
        target: ["x86_64-unknown-linux-gnu", "thumbv7em-none-eabihf", "thumbv6m-none-eabi"]
    env:
      FEATURE_COMBINATIONS: ";defmt"
    steps:
      - uses: actions/checkout@v4
      - name: Print rust version
        run: |
          rustc --version
          cargo --version
      - name: Build
        run: |
          export IFS=";"
          for features in $FEATURE_COMBINATIONS; do
            echo "::group::Features: \"$features\""
            cargo build -p lokey-usb-ble --verbose --target ${{ matrix.target }} --no-default-features --features "$features"
            echo "::endgroup::"
          done
      - name: Run clippy
        run: |
          export IFS=";"
          for features in $FEATURE_COMBINATIONS; do
            echo "::group::Features: \"$features\""
            cargo clippy -p lokey-usb-ble --verbose --target ${{ matrix.target }} --no-default-features --features "$features"
            echo "::endgroup::"
          done
      - name: Run tests
        if: matrix.target == 'x86_64-unknown-linux-gnu'
        run: |
          cargo test -p lokey-usb-ble --verbose --target ${{ matrix.target }}
  lokey-nrf:
    runs-on: ubuntu-latest
    if: always()
    strategy:
      fail-fast: false
      matrix:
        mcu: [nrf52840]
        include:
          - mcu: nrf52840
            target: thumbv7em-none-eabihf
            mcu_features: "nrf52840"
    env:
      FEATURE_COMBINATIONS: ";defmt;defmt usb ble"
    steps:
      - uses: actions/checkout@v4
      - name: Print rust version
        run: |
          rustc --version
          cargo --version
      - name: Build
        run: |
          export IFS=";"
          for features in $FEATURE_COMBINATIONS; do
            echo "::group::Features: \"$features ${{ matrix.mcu_features }}\""
            cargo build -p lokey-nrf --verbose --target ${{ matrix.target }} --no-default-features --features "$features ${{ matrix.mcu_features }}"
            echo "::endgroup::"
          done
      - name: Run clippy
        run: |
          export IFS=";"
          for features in $FEATURE_COMBINATIONS; do
            echo "::group::Features: \"$features ${{ matrix.mcu_features }}\""
            cargo clippy -p lokey-nrf --verbose --target ${{ matrix.target }} --no-default-features --features "$features ${{ matrix.mcu_features }}"
            echo "::endgroup::"
          done
      - name: Run doc tests
        run: |
          cargo test -p lokey-nrf --verbose --doc --target ${{ matrix.target }} --features "${{ matrix.mcu_features }}"
  lokey-rp:
    runs-on: ubuntu-latest
    if: always()
    strategy:
      fail-fast: false
      matrix:
        mcu: [rp2040]
        include:
          - mcu: rp2040
            target: thumbv6m-none-eabi
            mcu_features: "rp2040"
    env:
      FEATURE_COMBINATIONS: ";defmt;defmt usb"
    steps:
      - uses: actions/checkout@v4
      - name: Print rust version
        run: |
          rustc --version
          cargo --version
      - name: Build
        run: |
          export IFS=";"
          for features in $FEATURE_COMBINATIONS; do
            echo "::group::Features: \"$features ${{ matrix.mcu_features }}\""
            cargo build -p lokey-rp --verbose --target ${{ matrix.target }} --no-default-features --features "$features ${{ matrix.mcu_features }}"
            echo "::endgroup::"
          done
      - name: Run clippy
        run: |
          export IFS=";"
          for features in $FEATURE_COMBINATIONS; do
            echo "::group::Features: \"$features ${{ matrix.mcu_features }}\""
            cargo clippy -p lokey-rp --verbose --target ${{ matrix.target }} --no-default-features --features "$features ${{ matrix.mcu_features }}"
            echo "::endgroup::"
          done
      - name: Run doc tests
        run: |
          cargo test -p lokey-rp --verbose --doc --target ${{ matrix.target }} --features "${{ matrix.mcu_features }}"
  lokey-keyboard:
    runs-on: ubuntu-latest
    if: always()
    strategy:
      fail-fast: false
      matrix:
        target: ["x86_64-unknown-linux-gnu", "thumbv7em-none-eabihf", "thumbv6m-none-eabi"]
    env:
      FEATURE_COMBINATIONS: ";macros;defmt;usb;ble;usb ble;usb-ble;macros defmt usb ble usb-ble"
    steps:
      - uses: actions/checkout@v4
      - name: Print rust version
        run: |
          rustc --version
          cargo --version
      - name: Build
        run: |
          export IFS=";"
          for features in $FEATURE_COMBINATIONS; do
            echo "::group::Features: \"$features\""
            cargo build -p lokey-keyboard --verbose --target ${{ matrix.target }} --no-default-features --features "$features"
            echo "::endgroup::"
          done
      - name: Run clippy
        run: |
          export IFS=";"
          for features in $FEATURE_COMBINATIONS; do
            echo "::group::Features: \"$features\""
            cargo clippy -p lokey-keyboard --verbose --target ${{ matrix.target }} --no-default-features --features "$features"
            echo "::endgroup::"
          done
      - name: Run tests
        if: matrix.target == 'x86_64-unknown-linux-gnu'
        run: |
          cargo test -p lokey-keyboard --verbose --target ${{ matrix.target }} --features "usb ble usb-ble"
  lokey-mouse:
    runs-on: ubuntu-latest
    if: always()
    strategy:
      fail-fast: false
      matrix:
        target: ["x86_64-unknown-linux-gnu", "thumbv7em-none-eabihf", "thumbv6m-none-eabi"]
    env:
      FEATURE_COMBINATIONS: ";defmt;keyboard-actions;usb;ble;defmt keyboard-actions usb ble"
    steps:
      - uses: actions/checkout@v4
      - name: Print rust version
        run: |
          rustc --version
          cargo --version
      - name: Build
        run: |
          export IFS=";"
          for features in $FEATURE_COMBINATIONS; do
            echo "::group::Features: \"$features\""
            cargo build -p lokey-mouse --verbose --target ${{ matrix.target }} --no-default-features --features "$features"
            echo "::endgroup::"
          done
      - name: Run clippy
        run: |
          export IFS=";"
          for features in $FEATURE_COMBINATIONS; do
            echo "::group::Features: \"$features\""
            cargo clippy -p lokey-mouse --verbose --target ${{ matrix.target }} --no-default-features --features "$features"
            echo "::endgroup::"
          done
      - name: Run tests
        if: matrix.target == 'x86_64-unknown-linux-gnu'
        run: |
          cargo test -p lokey-mouse --verbose --target ${{ matrix.target }} --features "keyboard-actions usb ble"
  lokey-midi:
    runs-on: ubuntu-latest
    if: always()
    strategy:
      fail-fast: false
      matrix:
        target: ["x86_64-unknown-linux-gnu", "thumbv7em-none-eabihf", "thumbv6m-none-eabi"]
    env:
      FEATURE_COMBINATIONS: ";defmt;keyboard-actions;usb;ble;defmt keyboard-actions usb ble"
    steps:
      - uses: actions/checkout@v4
      - name: Print rust version
        run: |
          rustc --version
          cargo --version
      - name: Build
        run: |
          export IFS=";"
          for features in $FEATURE_COMBINATIONS; do
            echo "::group::Features: \"$features\""
            cargo build -p lokey-midi --verbose --target ${{ matrix.target }} --no-default-features --features "$features"
            echo "::endgroup::"
          done
      - name: Run clippy
        run: |
          export IFS=";"
          for features in $FEATURE_COMBINATIONS; do
            echo "::group::Features: \"$features\""
            cargo clippy -p lokey-midi --verbose --target ${{ matrix.target }} --no-default-features --features "$features"
            echo "::endgroup::"
          done
      - name: Run tests
        if: matrix.target == 'x86_64-unknown-linux-gnu'
        run: |
          cargo test -p lokey-midi --verbose --target ${{ matrix.target }} --features "keyboard-actions usb ble"
  lokey-layer:
    runs-on: ubuntu-latest
    if: always()
    strategy:
      fail-fast: false
      matrix:
        target: ["x86_64-unknown-linux-gnu", "thumbv7em-none-eabihf", "thumbv6m-none-eabi"]
    env:
      FEATURE_COMBINATIONS: ";defmt"
    steps:
      - uses: actions/checkout@v4
      - name: Print rust version
        run: |
          rustc --version
          cargo --version
      - name: Build
        run: |
          export IFS=";"
          for features in $FEATURE_COMBINATIONS; do
            echo "::group::Features: \"$features\""
            cargo build -p lokey-layer --verbose --target ${{ matrix.target }} --no-default-features --features "$features"
            echo "::endgroup::"
          done
      - name: Run clippy
        run: |
          export IFS=";"
          for features in $FEATURE_COMBINATIONS; do
            echo "::group::Features: \"$features\""
            cargo clippy -p lokey-layer --verbose --target ${{ matrix.target }} --no-default-features --features "$features"
            echo "::endgroup::"
          done
      - name: Run tests
        if: matrix.target == 'x86_64-unknown-linux-gnu'
        run: |
          cargo test -p lokey-layer --verbose --target ${{ matrix.target }}
  lokey-led-array:
    runs-on: ubuntu-latest
    if: always()
    strategy:
      fail-fast: false
      matrix:
        mcu: [no_mcu, nrf52840]
        include:
          - mcu: no_mcu
            target: x86_64-unknown-linux-gnu
            mcu_features: ""
          - mcu: nrf52840
            target: thumbv7em-none-eabihf
            mcu_features: "nrf52840"
    env:
      FEATURE_COMBINATIONS: ";defmt;ble;defmt ble"
    steps:
      - uses: actions/checkout@v4
      - name: Print rust version
        run: |
          rustc --version
          cargo --version
      - name: Build
        run: |
          export IFS=";"
          for features in $FEATURE_COMBINATIONS; do
            echo "::group::Features: \"$features ${{ matrix.mcu_features }}\""
            cargo build -p lokey-led-array --verbose --target ${{ matrix.target }} --no-default-features --features "$features ${{ matrix.mcu_features }}"
            echo "::endgroup::"
          done
      - name: Run clippy
        run: |
          export IFS=";"
          for features in $FEATURE_COMBINATIONS; do
            echo "::group::Features: \"$features ${{ matrix.mcu_features }}\""
            cargo clippy -p lokey-led-array --verbose --target ${{ matrix.target }} --no-default-features --features "$features ${{ matrix.mcu_features }}"
            echo "::endgroup::"
          done
      - name: Run doc tests
        if: matrix.target == 'x86_64-unknown-linux-gnu'
        run: |
          cargo test -p lokey-led-array --verbose --target ${{ matrix.target }} --features "ble"
  examples:
    runs-on: ubuntu-latest
    if: always()
    strategy:
      fail-fast: false
      matrix:
        example: [lokey-blink, keyboard-nrf52840, keyboard-rp2040]
        include:
          - example: lokey-blink
            feature_combinations: ";defmt"
          - example: keyboard-nrf52840
            feature_combinations: ";defmt"
          - example: keyboard-rp2040
            feature_combinations: ";defmt"
    env:
      FEATURE_COMBINATIONS: "${{ matrix.feature_combinations }}"
    steps:
      - uses: actions/checkout@v4
      - name: Print rust version
        run: |
          rustc --version
          cargo --version
      - name: Check formatting
        run: cargo fmt --verbose --check
        working-directory: examples/${{ matrix.example }}
      - name: Build
        run: |
          export IFS=";"
          for features in $FEATURE_COMBINATIONS; do
            echo "::group::Features: \"$features\""
            cargo build --verbose --no-default-features --features "$features"
            echo "::endgroup::"
          done
        working-directory: examples/${{ matrix.example }}
      - name: Run clippy
        run: |
          export IFS=";"
          for features in $FEATURE_COMBINATIONS; do
            echo "::group::Features: \"$features\""
            cargo clippy --verbose --no-default-features --features "$features"
            echo "::endgroup::"
          done
        working-directory: examples/${{ matrix.example }}
