[target.thumbv6m-none-eabi]
runner = "probe-rs run --chip RP2040"

[build]
target = "thumbv6m-none-eabi"

[profile.dev]
lto = true
opt-level = "s"
codegen-units = 1

[profile.release]
lto = true
opt-level = "s"
incremental = false
codegen-units = 1
debug = 2

[env]
DEFMT_LOG = "debug"
